#!/usr/bin/env bash

mkdir -p $HOME/code/tools
mkdir -p $HOME/code/projects
mkdir -p $HOME/code/playground
mkdir -p $HOME/code/test

cp flake.nix $HOME/code/flake.nix

sudo apt install curl

cd $HOME/Downloads/
sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon
. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

sudo echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

sudo apt purge curl

cd $HOME/code/
nix profile add .#all

cd $HOME/Downloads/

# wallpapers
echo "Downloading the waifus..."
git clone https://github.com/mathiasdonoso/anime.git ~/Pictures/anime

# fonts
mkdir -p /usr/local/share/fonts

# monoid font
echo "Downloading fonts..."
curl -L 'https://cdn.rawgit.com/larsenwork/monoid/2db2d289f4e61010dd3f44e09918d9bb32fb96fd/Monoid.zip' -o Monoid.zip
unzip 'Monoid.zip'
sudo mv Monoid*.ttf /usr/local/share/fonts/
rm Readme*.html
rm Monoid.zip

sudo fc-cache

# dotfiles
echo "Configuring dotfiles..."
cd $HOME
git clone --recurse-submodules https://github.com/mathiasdonoso/dotfiles.git
rm .bashrc
cd dotfiles
stow .

echo "Please run: source ~/.bashrc or restart your terminal."
