#!/usr/bin/env bash

git clone https://github.com/neovim/neovim.git $HOME/code/tools/neovim
cd $HOME/code/tools/neovim
git fetch
git checkout v0.11.0

sudo apt install cmake gettext lua5.1 liblua5.1-0-dev
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
